workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: experiments/onboarding_reference/flutter
    integrations:
      app_store_connect: Codemagic API
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build iOS
        script: flutter build ipa --release
    artifacts:
      - experiments/onboarding_reference/flutter/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
